package s21.palvelinohjelmointi.harjoitustyo.domain;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

//tells Java this class has a matching table in the database
@Entity
public class Flower {
	
	//attributes of Flower-class
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;
	//validation
	@NotNull
	@Size(min = 3, max = 40)
	private String name;
	private String info;
	@Min(value = 1, message = "Price must be at least 1 euro")
	private int price;
	
	
	//prevents forever loop in REST api JSON query
	@JsonIgnoreProperties("flowercategory")
	//JPA (Java Persistance API functionalities for database operations
	@ManyToOne
	@JoinColumn(name = "flowercategoryid")
	private Flowercategory flowercategory;
	
	@JsonIgnoreProperties("flowerphoto")
	@ManyToOne
	@JoinColumn(name = "flowerphotoid")
	private Flowerphoto flowerphoto;
	
	
	//constructors, note: id can´t be constructed because it is autogenerated
	
	public Flower() {}

	public Flower(@NotNull @Size(min = 3, max = 40) String name, String info, int price,
			Flowercategory flowercategory, Flowerphoto flowerphoto) {
		super();
		this.name = name;
		this.info = info;
		this.price = price;
		this.flowercategory = flowercategory;
		this.flowerphoto = flowerphoto;
	}
	
	public Flower(@NotNull @Size(min = 3, max = 40) String name, String info, int price,
			Flowercategory flowercategory) {
		super();
		this.name = name;
		this.info = info;
		this.price = price;
		this.flowercategory = flowercategory;
		
	}
	
	public Flower(@NotNull @Size(min = 3, max = 40) String name, String info, int price) {
		super();
		this.name = name;
		this.info = info;
		this.price = price;
	}
	
	//getters and setters

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Flowercategory getFlowercategory() {
		return flowercategory;
	}

	public void setFlowercategory(Flowercategory flowercategory) {
		this.flowercategory = flowercategory;
	}
	
	public Flowerphoto getFlowerphoto() {
		return flowerphoto;
	}

	public void setFlowerphoto(Flowerphoto flowerphoto) {
		this.flowerphoto = flowerphoto;
	}

	@Override
	public String toString() {
		return "Flower [id = " + id + ", name = " + name + ", info = " + info + ", price = " + price + "category = " + flowercategory + "]";
	}
	

	

}
